kind: pipeline
name: pandoc-arm

steps:
- name: arm-stack-ghc863
  image: ann17/pandoc-ghc-arm:stack-ghc8.6.3
  privileged: true
  commands:
  - ./stack/chroot.sh arm
- name: aarch64-stack-ghc862
  image: ann17/pandoc-ghc-aarch64:stack-ghc8.6.2
  privileged: true
  commands:
  - ./stack/chroot.sh
- name: arm-cabal-ghc802
  image: ann17/pandoc-ghc-arm:cabal-ghc8.0.2
  privileged: true
  commands:
  - ./cabal/chroot.sh arm
- name: aarch64-cabal-ghc802
  image: ann17/pandoc-ghc-aarch64:cabal-ghc8.0.2
  privileged: true
  commands:
  - ./cabal/chroot.sh

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: /drone/src/bin/*
  checksum:
  - sha1
  - md5
  when:
    event: tag
    
