kind: pipeline
name: pandoc-arm

steps:
- name: arm
  image: ann17/pandoc-ghc-arm
  privileged: true
  commands:
  - ./chroot.sh arm
- name: aarch64
  image: ann17/pandoc-ghc-aarch64
  privileged: true
  commands:
  - ./chroot.sh

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: /drone/src/bin/*
  checksum:
  - sha1
  - md5
  when:
    event: tag
    
