kind: pipeline
name: pandoc-arm

steps:
- name: arm-cabal-ghc865
  image: ann17/pandoc-ghc-arm:cabal-ghc8.6.5
  pull: always
  privileged: true
  commands:
  - ./cabal/chroot.sh arm
- name: aarch64-cabal-ghc865
  image: ann17/pandoc-ghc-aarch64:cabal-ghc8.6.5
  pull: always
  privileged: true
  commands:
  - ./cabal/chroot.sh
- name: aarch64-alpinestack-ghc862
  image: ann17/pandoc-ghc-aarch64:alpinestack-ghc8.6.2
  pull: always
  privileged: true
  commands:
  - ./alpine-stack/chroot.sh

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: /drone/src/bin/*
  checksum:
  - sha1
  - md5
  when:
    event: tag
    
