name: Pandoc armv7l

on: [push]

jobs:

  armv7l-cabal-ghc865:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static aria2
        aria2c -x 16 http://cdimage.ubuntu.com/ubuntu-base/releases/19.10/release/ubuntu-base-19.10-base-armhf.tar.gz
        mkdir rootfs
        mkdir bin
        cd rootfs
        tar xvf ../ubuntu-base-19.10-base-armhf.tar.gz
        cp /usr/bin/qemu-arm-static usr/bin
        cp /etc/resolv.conf etc
        cp ../build.sh .
        sudo mount -t devtmpfs devtmpfs dev
        sudo mount -t devpts devpts dev/pts
        sudo mount -t sysfs sysfs sys
        sudo mount -t tmpfs tmpfs tmp
        sudo mount -t proc proc proc
        sudo chroot . /build.sh
        curl -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/x-gzip" "https://uploads.github.com/repos/arm4rpi/pandoc-arm/releases/24335813/assets?name=aarch64-pandoc-2.9.2.tar.gz" --data-binary @aarch64-pandoc-2.9.2.tar.gz
        mv root/bin/* ../bin

    - uses: actions/upload-artifact@master
      with:
        name: pandoc-${GITHUB_REF}-armv7l
        path: bin
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false      
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: bin/*.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
