name: Pandoc Arm

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: armv7l
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-arm:latest /drone/src/chroot.sh arm
    - name: aarch64
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-aarch64:latest /drone/src/chroot.sh
