name: Pandoc Arm

on: [push]

jobs:

  armv7l:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chroot
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-arm:latest ./chroot.sh arm

  aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: chroot
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-aarch64:latest ./chroot.sh
