name: Pandoc Arm

on: [push]

jobs:
  x86_64:

    runs-on: ubuntu-latest
    steps:
    - name: Clone Pandoc
      run: |
          git clone https://github.com/jgm/pandoc
    - name: Install recent cabal/ghc
      run: |
          sudo add-apt-repository ppa:hvr/ghc
          sudo apt-get update
          sudo apt-get install ghc-8.6.5 cabal-install-2.4 xz-utils
    - name: Install dependencies
      run: |
          export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH
          cd pandoc
          cabal v2-update
          cabal v2-build --dependencies-only . pandoc-citeproc
    - name: Build
      run: |
          export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH
          cd pandoc
          cabal v2-install . pandoc-citeproc
          strip $HOME/.cabal/bin/pandoc
          strip $HOME/.cabal/bin/pandoc-citeproc
    - name: Install artifact
      run: |
          export ARTIFACTS=bin/
          mkdir -p ${ARTIFACTS}
          cd pandoc
          export tag=`git describe --tags`
          cp $HOME/.cabal/bin/pandoc ${ARTIFACTS}/pandoc-${tag}-x86_64
          cp $HOME/.cabal/bin/pandoc-citeproc ${ARTIFACTS}/pandoc-citeproc-${tag}-x86-64
          xz ${ARTIFACTS}/*
    - uses: actions/upload-artifact@master
      with:
        name: bin
        path: bin

  aarch64:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: chroot
      run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static xz-utils
          mkdir rootfs
          aria2c -x 16 http://cdimage.ubuntu.com/ubuntu-base/releases/19.10/release/ubuntu-base-19.10-base-arm64.tar.gz --out=ubuntu-aarch64.tar.gz
          cd rootfs
          tar xvf ../ubuntu-aarch64.tar.gz
          cp ../build.sh .
          cp /usr/bin/qemu-aarch64-static usr/bin
          cp /etc/resolv.conf etc
          sudo mount -t devtmpfs devtmpfs dev
          sudo mount -t devpts devpts dev/pts
          sudo mount -t sysfs sysfs sys
          sudo mount -t tmpfs tmpfs tmp
          sudo mount -t proc proc proc
          sudo chroot . /build.sh
          
          cd ../
          export ARTIFACTS=bin/
          mkdir -p {$ARTIFACTS}
          cp rootfs/root/.cabal/bin/* ${ARTIFACTS}/
    - uses: actions/upload-artifact@master
      with:
        name: bin
        path: bin

  armv7l:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: chroot
      run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static xz-utils aria2
          mkdir rootfs
          aria2c -x 16 http://cdimage.ubuntu.com/ubuntu-base/releases/19.10/release/ubuntu-base-19.10-base-armhf.tar.gz --out=ubuntu-arm.tar.gz
          cd rootfs
          tar xvf ../ubuntu-arm.tar.gz
          cp ../build.sh .
          cp /usr/bin/qemu-arm-static usr/bin
          cp /etc/resolv.conf etc
          sudo mount -t devtmpfs devtmpfs dev
          sudo mount -t devpts devpts dev/pts
          sudo mount -t sysfs sysfs sys
          sudo mount -t tmpfs tmpfs tmp
          sudo mount -t proc proc proc
          sudo chroot . /build.sh
          
          cd ../
          export ARTIFACTS=bin/
          mkdir -p {$ARTIFACTS}
          cp rootfs/root/.cabal/bin/* ${ARTIFACTS}/
    - uses: actions/upload-artifact@master
      with:
        name: bin
        path: bin

