name: Pandoc Arm

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-get install docker-ce
    - name: Check Docker Version
      run: docker --version
    - name: armv7l
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-arm:latest /drone/src/chroot.sh arm
    - name: aarch64
      run: docker run --privileged -v $(pwd):/drone/src ann17/pandoc-ghc-aarch64:latest /drone/src/chroot.sh
